#! /bin/sh

### BEGIN INIT INFO
# Provides:          Sick Beard application instance
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of Sick Beard
# Description:       starts instance of Sick Beard using start-stop-daemon
### END INIT INFO

### DON'T EDIT ME
## place your customizations to these variables in
## the appropriate location for your distribution and
## symlink this file to the appropriate location for
## your distribution
###

###
## debian/ubuntu usage example:
##  one install:
##   _symlink_ this script to /etc/init.d/sickbeard
##   _copy_ initscript_config to /etc/defaults/sickbeard
##
##  multiple installs:
##   copied config file name must match the name 
##   you use for the symlink
##   in /etc/init.d.
##   e.g.:
##   initscript symlinked to /etc/init.d/mygreatsickbeard1
##   config _copied_ /etc/default/mygreatsickbeard1
##   and
##   initscript symlinked to /etc/init.d/mygreatsickbeard2
##   config _copied_ to /etc/default/mygreatsickbeard2
##
## 
###

# path to app
APP_PATH=PATH_TO_SICKBEARD_DIRECTORY

# path to python bin
DAEMON=/usr/bin/python

# startup args
DAEMON_OPTS=" SickBeard.py -q"

# script name
NAME=sickbeard

# app name
DESC=SickBeard

# user
RUN_AS=SICKBEARD_USER

PID_FILE=/var/run/sickbeard.pid

# initscript name
INITSCRIPT="$(basename "$0")"

# debian, ubuntu place initscript customizations here
if [ -r /etc/default/${INITSCRIPT} ]; then
	. /etc/default/${INITSCRIPT}
fi

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
        echo "Starting $DESC"
        start-stop-daemon -d $APP_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
        ;;
  stop)
        echo "Stopping $DESC"
        start-stop-daemon --stop --pidfile $PID_FILE
        ;;

  restart|force-reload)
        echo "Restarting $DESC"
        start-stop-daemon --stop --pidfile $PID_FILE
        sleep 15
        start-stop-daemon -d $APP_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
