__title__ = 'subliminal'
__description__ = 'Subtitles, faster than your thoughts'
__version__ = '0.5'
__author__ = 'Antoine Bertin'
__license__ = 'LGPLv3'
__copyright__ = 'Copyright 2010-2011 Antoine Bertin'
