ren "++n copia.png"                                             "++n.png"                                               
ren "1live copia.png"                                           "1live.png"                                             
ren "33 copia.png"                                              "33.png"                                                
ren "3fm copia.png"                                             "3fm.png"                                               
ren "3sat copia.png"                                            "3sat.png"                                              
ren "7mate copia.png"                                           "7mate.png"                                             
ren "a&e copia.png"                                             "a&e.png"                                               
ren "aande copia.png"                                           "aande.png"                                             
ren "ABC (Australia) copia.png"                                 "ABC (Australia).png"                                   
ren "abc copia.png"                                             "abc.png"                                               
ren "ABC Family copia.png"                                      "ABC Family.png"                                        
ren "abc news copia.png"                                        "abc news.png"                                          
ren "adult swim copia.png"                                      "adult swim.png"                                        
ren "adult-swim copia.png"                                      "adult-swim.png"                                        
ren "adultswim copia.png"                                       "adultswim.png"                                         
ren "amc copia.png"                                             "amc.png"                                               
ren "animal planet copia.png"                                   "animal planet.png"                                     
ren "animalplanet copia.png"                                    "animalplanet.png"                                      
ren "Animax copia.png"                                          "Animax.png"                                            
ren "anime network copia.png"                                   "anime network.png"                                     
ren "Antena-3 copia.png"                                        "Antena-3.png"                                          
ren "ard copia.png"                                             "ard.png"                                               
ren "arte copia.png"                                            "arte.png"                                              
ren "AT-X copia.png"                                            "AT-X.png"                                              
ren "at5 copia.png"                                             "at5.png"                                               
ren "AVRO copia.png"                                            "AVRO.png"                                              
ren "Bandai copia.png"                                          "Bandai.png"                                            
ren "Bandai Visual copia.png"                                   "Bandai Visual.png"                                     
ren "bbc america copia.png"                                     "bbc america.png"                                       
ren "bbc copia.png"                                             "bbc.png"                                               
ren "bbc entertainment copia.png"                               "bbc entertainment.png"                                 
ren "bbc four copia.png"                                        "bbc four.png"                                          
ren "bbc one copia.png"                                         "bbc one.png"                                           
ren "bbc prime copia.png"                                       "bbc prime.png"                                         
ren "bbc three copia.png"                                       "bbc three.png"                                         
ren "bbc two copia.png"                                         "bbc two.png"                                           
ren "bio. copia.png"                                            "bio..png"                                              
ren "Biography-Channel copia.png"                               "Biography-Channel.png"                                 
ren "bloomberg copia.png"                                       "bloomberg.png"                                         
ren "bnn copia.png"                                             "bnn.png"                                               
ren "bravo copia.png"                                           "bravo.png"                                             
ren "canal+ copia.png"                                          "canal+.png"                                            
ren "canvas copia.png"                                          "canvas.png"                                            
ren "cartoon network copia.png"                                 "cartoon network.png"                                   
ren "cartoonnetwork copia.png"                                  "cartoonnetwork.png"                                    
ren "cbbc copia.png"                                            "cbbc.png"                                              
ren "CBC copia.png"                                             "CBC.png"                                               
ren "CBeebies copia.png"                                        "CBeebies.png"                                          
ren "cbs copia.png"                                             "cbs.png"                                               
ren "channel ten copia.png"                                     "channel ten.png"                                       
ren "channel4 copia.png"                                        "channel4.png"                                          
ren "cnn copia.png"                                             "cnn.png"                                               
ren "comedy central copia.png"                                  "comedy central.png"                                    
ren "comedy central Family copia.png"                           "comedy central Family.png"                             
ren "comedy central HD copia.png"                               "comedy central HD.png"                                 
ren "comedy entral old copia.png"                               "comedy entral old.png"                                 
ren "comedycentral copia.png"                                   "comedycentral.png"                                     
ren "ctv copia.png"                                             "ctv.png"                                               
ren "cuatro copia.png"                                          "cuatro.png"                                            
ren "cw copia.png"                                              "cw.png"                                                
ren "discovery channel copia.png"                               "discovery channel.png"                                 
ren "discovery copia.png"                                       "discovery.png"                                         
ren "discoverychannel copia.png"                                "discoverychannel.png"                                  
ren "disney channel copia.png"                                  "disney channel.png"                                    
ren "disney copia.png"                                          "disney.png"                                            
ren "Disney XD copia.png"                                       "Disney XD.png"                                         
ren "disneychannel copia.png"                                   "disneychannel.png"                                     
ren "diy network copia.png"                                     "diy network.png"                                       
ren "DMAX copia.png"                                            "DMAX.png"                                              
ren "e! copia.png"                                              "e!.png"                                                
ren "e4 copia.png"                                              "e4.png"                                                
ren "einslive copia.png"                                        "einslive.png"                                          
ren "endemol copia.png"                                         "endemol.png"                                           
ren "entertainment copia.png"                                   "entertainment.png"                                     
ren "eredivisie live 1 copia.png"                               "eredivisie live 1.png"                                 
ren "eredivisie live 2 copia.png"                               "eredivisie live 2.png"                                 
ren "eredivisie live copia.png"                                 "eredivisie live.png"                                   
ren "espn copia.png"                                            "espn.png"                                              
ren "eurosport 1 copia.png"                                     "eurosport 1.png"                                       
ren "eurosport 2 copia.png"                                     "eurosport 2.png"                                       
ren "eurosport copia.png"                                       "eurosport.png"                                         
ren "eurosport HD copia.png"                                    "eurosport HD.png"                                      
ren "file.txt                                                   "ile.txt                                              
ren "five copia.png"                                            "five.png"                                              
ren "food network copia.png"                                    "food network.png"                                      
ren "fox copia.png"                                             "fox.png"                                               
ren "fox television classics copia.png"                         "fox television classics.png"                           
ren "France 2 copia.png"                                        "France 2.png"                                          
ren "France 3 copia.png"                                        "France 3.png"                                          
ren "Fuji-TV copia.png"                                         "Fuji-TV.png"                                           
ren "funimation copia.png"                                      "funimation.png"                                        
ren "fx copia.png"                                              "fx.png"                                                
ren "fxnetworks copia.png"                                      "fxnetworks.png"                                        
ren "G4 copia.png"                                              "G4.png"                                                
ren "G4_2 copia.png"                                            "G4_2.png"                                              
ren "Game Show Network copia.png"                               "Game Show Network.png"                                 
ren "Global-TV copia.png"                                       "Global-TV.png"                                         
ren "hbo copia.png"                                             "hbo.png"                                               
ren "HDNet copia.png"                                           "HDNet.png"                                             
ren "history copia.png"                                         "history.png"                                           
ren "historychannel copia.png"                                  "historychannel.png"                                    
ren "hulu copia.png"                                            "hulu.png"                                              
ren "hulu presents copia.png"                                   "hulu presents.png"                                     
ren "IFC copia.png"                                             "IFC.png"                                               
ren "itv copia.png"                                             "itv.png"                                               
ren "ITV1 copia.png"                                            "ITV1.png"                                              
ren "ketnet copia.png"                                          "ketnet.png"                                            
ren "KRO copia.png"                                             "KRO.png"                                               
ren "lasexta copia.png"                                         "lasexta.png"                                           
ren "lifetime copia.png"                                        "lifetime.png"                                          
ren "M6 copia.png"                                              "M6.png"                                                
ren "Manhattan Neighborhood Network copia.png"                  "Manhattan Neighborhood Network.png"                    
ren "MDR copia.png"                                             "MDR.png"                                               
ren "motorvision copia.png"                                     "motorvision.png"                                       
ren "motorvision tv copia.png"                                  "motorvision tv.png"                                    
ren "mtv copia.png"                                             "mtv.png"                                               
ren "Nat Geo Wild copia.png"                                    "Nat Geo Wild.png"                                      
ren "National Geographic copia.png"                             "National Geographic.png"                               
ren "nbc copia.png"                                             "nbc.png"                                               
ren "NBCU TV copia.png"                                         "NBCU TV.png"                                           
ren "NDR copia.png"                                             "NDR.png"                                               
ren "nederland 1 copia.png"                                     "nederland 1.png"                                       
ren "nederland 2 copia.png"                                     "nederland 2.png"                                       
ren "nederland 3 copia.png"                                     "nederland 3.png"                                       
ren "net 5 copia.png"                                           "net 5.png"                                             
ren "net5 copia.png"                                            "net5.png"                                              
ren "Network Ten copia.png"                                     "Network Ten.png"                                       
ren "ngc copia.png"                                             "ngc.png"                                               
ren "Nick at Nite copia.png"                                    "Nick at Nite.png"                                      
ren "nickelodeon copia.png"                                     "nickelodeon.png"                                       
ren "NickToons Network copia.png"                               "NickToons Network.png"                                 
ren "ORF copia.png"                                             "ORF.png"                                               
ren "ORF1 HD copia.png"                                         "ORF1 HD.png"                                           
ren "oxygen copia.png"                                          "oxygen.png"                                            
ren "pbs copia.png"                                             "pbs.png"                                               
ren "Playboy TV copia.png"                                      "Playboy TV.png"                                        
ren "private spice copia.png"                                   "private spice.png"                                     
ren "Pro7 copia.png"                                            "Pro7.png"                                              
ren "Production I.G. copia.png"                                 "Production I.G..png"                                   
ren "radio west copia.png"                                      "radio west.png"                                        
ren "Revision3 copia.png"                                       "Revision3.png"                                         
ren "rtl 4 copia.png"                                           "rtl 4.png"                                             
ren "rtl 5 copia.png"                                           "rtl 5.png"                                             
ren "rtl 7 copia.png"                                           "rtl 7.png"                                             
ren "rtl 8 copia.png"                                           "rtl 8.png"                                             
ren "rtl4 copia.png"                                            "rtl4.png"                                              
ren "rtl5 copia.png"                                            "rtl5.png"                                              
ren "rtl7 copia.png"                                            "rtl7.png"                                              
ren "rtl8 copia.png"                                            "rtl8.png"                                              
ren "Sat1 copia.png"                                            "Sat1.png"                                              
ren "sbs 6 copia.png"                                           "sbs 6.png"                                             
ren "SBS copia.png"                                             "SBS.png"                                               
ren "sbs6 copia.png"                                            "sbs6.png"                                              
ren "scifi copia.png"                                           "scifi.png"                                             
ren "Seven Network copia.png"                                   "Seven Network.png"                                     
ren "Showcase copia.png"                                        "Showcase.png"                                          
ren "showtime copia.png"                                        "showtime.png"                                          
ren "sky copia.png"                                             "sky.png"                                               
ren "sky1 copia.png"                                            "sky1.png"                                              
ren "Speed Channel copia.png"                                   "Speed Channel.png"                                     
ren "Spike TV copia.png"                                        "Spike TV.png"                                          
ren "starz copia.png"                                           "starz.png"                                             
ren "starz! copia.png"                                          "starz!.png"                                            
ren "style network copia.png"                                   "style network.png"                                     
ren "Sunrise copia.png"                                         "Sunrise.png"                                           
ren "Super Channel copia.png"                                   "Super Channel.png"                                     
ren "syfy copia.png"                                            "syfy.png"                                              
ren "TBS copia.png"                                             "TBS.png"                                               
ren "TBS Superstation copia.png"                                "TBS Superstation.png"                                  
ren "Telecinco copia.png"                                       "Telecinco.png"                                         
ren "the cw copia.png"                                          "the cw.png"                                            
ren "The Movie Network copia.png"                               "The Movie Network.png"                                 
ren "the wb copia.png"                                          "the wb.png"                                            
ren "the-cw copia.png"                                          "the-cw.png"                                            
ren "thecw copia.png"                                           "thecw.png"                                             
ren "thewb copia.png"                                           "thewb.png"                                             
ren "tmf copia.png"                                             "tmf.png"                                               
ren "tnt copia.png"                                             "tnt.png"                                               
ren "toei animation copia.png"                                  "toei animation.png"                                    
ren "Tokyo Mx copia.png"                                        "Tokyo Mx.png"                                          
ren "tv guide copia.png"                                        "tv guide.png"                                          
ren "TV Tokyo copia.png"                                        "TV Tokyo.png"                                          
ren "tv west copia.png"                                         "tv west.png"                                           
ren "tv3 copia.png"                                             "tv3.png"                                               
ren "tve1, la 1 copia.png"                                      "tve1, la 1.png"                                        
ren "tve2, la 2 copia.png"                                      "tve2, la 2.png"                                        
ren "UPN copia.png"                                             "UPN.png"                                               
ren "USA copia.png"                                             "USA.png"                                               
ren "usa network copia.png"                                     "usa network.png"                                       
ren "usa-network copia.png"                                     "usa-network.png"                                       
ren "usanetwork copia.png"                                      "usanetwork.png"                                        
ren "vara copia.png"                                            "vara.png"                                              
ren "veronica copia.png"                                        "veronica.png"                                          
ren "vh1 copia.png"                                             "vh1.png"                                               
ren "VIZ Media copia.png"                                       "VIZ Media.png"                                         
ren "VOX copia.png"                                             "VOX.png"                                               
ren "vpro copia.png"                                            "vpro.png"                                              
ren "vtm copia.png"                                             "vtm.png"                                               
ren "Xebec copia.png"                                           "Xebec.png"                                             